# Generated by Django 6.0.4 on 2026-04-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_event_image_url_club_logo_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_recruiting',
            field=models.BooleanField(default=False),
        ),
    ]
