# Generated by Django 6.0.4 on 2026-04-27 19:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_club_is_recruiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_core_team_recruiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='leader',
            field=models.CharField(blank=True, help_text='Name of the club leader', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CoreTeamApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Event', 'Event'), ('Design', 'Design'), ('Sponsorship', 'Sponsorship'), ('Project', 'Project'), ('Social Media', 'Social Media')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_team_apps', to='app.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_team_apps', to='app.student')),
            ],
        ),
    ]
