# Generated by Django 6.0.4 on 2026-04-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_club_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_core_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('school', 'School'), ('club', 'Club'), ('general', 'General'), ('core_team', 'Core Team Recruitment')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='coreteamapplication',
            name='department',
            field=models.CharField(choices=[('Event', 'Event'), ('Design', 'Design'), ('Sponsorship', 'Sponsorship'), ('Project', 'Project'), ('Social Media', 'Social Media'), ('Coordinator', 'Coordinator')], max_length=50),
        ),
    ]
